### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by zero323** [awesome-spark/scoring-heart-disease#2]
It would be a good idea to specify license (either for each example or a whole repository).

**Comment by eliasah** [comment]
sure, the whole repo seems good to me, any suggestions ?

**Comment by zero323** [comment]
CC BY-SA 4.0? Unless you consider the code valuable enough to use more code-aware license.

**Comment by eliasah** [comment]
do you mean like the one in https://github.com/awesome-spark/awesome-spark#license ?

**Comment by zero323** [comment]
More [https://creativecommons.org/licenses/by-sa/4.0/](https://creativecommons.org/licenses/by-sa/4.0/)

 https://creativecommons.org/choose/

**Comment by eliasah** [comment]
But it isn't possible to add both of us in the licence ?

**Comment by eliasah** [comment]
#5 Should close this issue
