### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by zero323** [awesome-spark/scoring-heart-disease#3]
If #1  is merged we should rename repository. I've been thinking about spark-examples.

**Comment by eliasah** [comment]
or learn-by-examples ?

**Comment by zero323** [comment]
Fine by me.

**Comment by zero323** [comment]
@eliasah Choose the one you prefer. You can also look at #4

**Comment by eliasah** [comment]
I have renamed it `learn-by-examples`
